AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  NewCops: enable

Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
