AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  NewCops: enable

Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/AbcSize:
  Max: 100
Metrics/MethodLength:
  Max: 100
Metrics/BlockLength:
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 15
