docker:
  image: yegor256/blog-image
install: |
  sudo apt-get update
  sudo apt-get install -y woff2
  export GEM_HOME=~/.ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH
  bundle install
merge:
  script: |
    LC_ALL=en_US.UTF-8 bundle exec rake
