title: Егор Бугаенко о политике
email: yegor256@gmail.com
description: >
  Это русскоязычный раздел моего блога, где я
  пишу в основном о политике и в основном в Украине
baseurl: ""
url: "https://ru.yegor256.com"
twitter_username: yegor256
github_username: yegor256
markdown: kramdown
author:
  name: "Егор Бугаенко"
  email: yegor256@gmail.com
encoding: utf-8
timezone: Europe/Kiev
permalink: :year-:month-:day-:title.html
exclude:
  - README.md
  - Gemfile.lock
  - Gemfile
  - Rakefile
  - LICENSE.txt
  - id_rsa.enc

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-bits
  - jekyll-chatgpt-translate

chatgpt-translate:
  api_key_file: ../chatgpt-key.txt
  threshold: 5
  layout: english
  source: ru
  targets:
    -
      language: en
      permalink: :year-:month-:day-:slug-eng.html

paginate: 8
paginate_path: "p/:num"
excerpt_separator: <!--more-->

feed:
  title: ru.yegor256.com
  subtitle: Егор Бугаенко о политике
  path: rss.xml

sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false
