---
name: jekyll
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: cron
  cancel-in-progress: true
jobs:
  jekyll:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: sudo apt-get -y update --fix-missing
      - run: sudo apt-get -y install cmake
      - run: sudo apt-get -y install aspell aspell-en
      - run: sudo apt-get -y install graphviz
      - run: sudo apt-get -y install gnuplot
      - run: sudo apt-get -y install s3cmd
      - run: sudo apt-get -y install fontforge liblapack-dev
      - run: sudo apt-get -y install plantuml
      - run: sudo apt-get -y install libxml2-utils
      - run: sudo apt-get -y install woff2
      - run: |
          wget https://github.com/yegor256/blog-image/raw/master/woff.zip
          unzip woff.zip -d _sfnt2woff
          cd _sfnt2woff
          make
          sudo cp sfnt2woff /usr/local/bin/
          cd ..
          rm woff.zip
          rm -rf _sfnt2woff
      - run: |
          git clone https://github.com/htacg/tidy-html5.git _tidy-html5
          cd _tidy-html5/build/cmake
          git checkout 5.8.0
          cmake ../..
          make
          sudo make install
          cd ../../..
          rm -rf _tidy-html5
      - run: npm install -g cssshrink@0.0.5
      - run: npm install -g eslint@8.44.0
      - run: gem install fontcustom -v 2.0.0
      - run: bundle update
      - run: bundle exec rake
